import { v4 as uuidv4 } from 'uuid'
import { calcResult, type Transaction } from '@/types/transaction'

function dt(day: number, hour: number, minute = 0) {
  return `2026-05-${String(day).padStart(2, '0')}T${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}:00`
}

type RawTx = Omit<Transaction, 'result'> & { result?: Transaction['result'] }

export const SAMPLE_TRANSACTIONS: Transaction[] = ([
  {
    id: uuidv4(),
    entryTime: dt(1, 20, 15),
    order: 'Man City vs Arsenal - Over 2.5',
    orderType: 'bet_game',
    amount: 500_000,
    rate: 1.85,
    cutOrder: 'Under 2.5',
    cutAmount: 200_000,
    profit: 425_000,
    result: 'win',
    reason: 'Hai đội tấn công mạnh, lịch sử đối đầu nhiều bàn thắng, thời tiết tốt',
    createdAt: dt(1, 20, 15),
  },
  {
    id: uuidv4(),
    entryTime: dt(3, 21, 0),
    order: 'Real Madrid vs Bayern - Kèo châu Á +0.5',
    orderType: 'bet_game',
    amount: 1_000_000,
    rate: 0.95,
    profit: -1_000_000,
    result: 'lose',
    reason: 'Real đang form tốt ở Champions League, sân nhà có lợi thế',
    createdAt: dt(3, 21, 0),
  },
  {
    id: uuidv4(),
    entryTime: dt(5, 9, 30),
    order: 'BTC/USDT Long',
    orderType: 'trading',
    amount: 2_000_000,
    profit: 340_000,
    result: 'win',
    reason: 'Break out vùng kháng cự 68k, RSI chưa quá mua, volume tăng mạnh',
    createdAt: dt(5, 9, 30),
  },
  {
    id: uuidv4(),
    entryTime: dt(5, 14, 45),
    order: 'ETH/USDT Short',
    orderType: 'trading',
    amount: 1_500_000,
    profit: -280_000,
    result: 'lose',
    reason: 'Divergence RSI trên khung H4, giá chạm vùng kháng cự mạnh 3200',
    createdAt: dt(5, 14, 45),
  },
  {
    id: uuidv4(),
    entryTime: dt(8, 19, 45),
    order: 'Liverpool vs Chelsea - Liverpool thắng',
    orderType: 'bet_game',
    amount: 800_000,
    rate: 2.1,
    cutOrder: 'Hòa',
    cutAmount: 300_000,
    profit: 880_000,
    result: 'win',
    reason: 'Liverpool đang phong độ đỉnh cao, Chelsea thiếu trung vệ chính',
    createdAt: dt(8, 19, 45),
  },
  {
    id: uuidv4(),
    entryTime: dt(10, 10, 0),
    order: 'SOL/USDT Long',
    orderType: 'trading',
    amount: 3_000_000,
    profit: 0,
    result: 'draw',
    reason: 'Sideway trong kênh giá, vào lệnh sai thời điểm, đóng lệnh ở breakeven',
    createdAt: dt(10, 10, 0),
  },
  {
    id: uuidv4(),
    entryTime: dt(12, 21, 30),
    order: 'PSG vs Dortmund - Tài 3.5',
    orderType: 'bet_game',
    amount: 600_000,
    rate: 2.0,
    profit: -600_000,
    result: 'lose',
    reason: 'PSG tấn công mạnh, Dortmund hàng thủ có vấn đề gần đây',
    createdAt: dt(12, 21, 30),
  },
  {
    id: uuidv4(),
    entryTime: dt(14, 9, 0),
    order: 'BTC/USDT Long',
    orderType: 'trading',
    amount: 5_000_000,
    profit: 1_200_000,
    result: 'win',
    reason: 'Halving cycle bull run, giá test lại EMA 50 trên D1, confluence với Fibonacci 0.618',
    createdAt: dt(14, 9, 0),
  },
  {
    id: uuidv4(),
    entryTime: dt(16, 20, 0),
    order: 'Barcelona vs Atletico - Barca thắng',
    orderType: 'bet_game',
    amount: 700_000,
    rate: 1.75,
    cutOrder: 'Hòa hoặc Atletico thắng',
    cutAmount: 250_000,
    profit: 525_000,
    result: 'win',
    reason: 'Barca sân nhà mạnh, Atletico vắng Griezmann, Barca cần điểm cho top 4',
    createdAt: dt(16, 20, 0),
  },
  {
    id: uuidv4(),
    entryTime: dt(18, 11, 15),
    order: 'XRP/USDT Long',
    orderType: 'trading',
    amount: 2_500_000,
    profit: -450_000,
    result: 'lose',
    reason: 'Tin tức SEC thắng kiện, kỳ vọng pump mạnh nhưng bị sell the news',
    createdAt: dt(18, 11, 15),
  },
  {
    id: uuidv4(),
    entryTime: dt(20, 20, 45),
    order: 'Inter vs Juventus - Dưới 2.5',
    orderType: 'bet_game',
    amount: 400_000,
    rate: 1.9,
    profit: 360_000,
    result: 'win',
    reason: 'Derby d\'Italia thường ít bàn, hai đội đều phòng thủ chặt trước trận lớn',
    createdAt: dt(20, 20, 45),
  },
  {
    id: uuidv4(),
    entryTime: dt(22, 8, 30),
    order: 'ETH/USDT Long',
    orderType: 'trading',
    amount: 4_000_000,
    profit: 780_000,
    result: 'win',
    reason: 'ETH ETF approval catalyst, giá vượt kháng cự 3400 với volume lớn',
    createdAt: dt(22, 8, 30),
  },
] as RawTx[]).map((tx) => ({ ...tx, result: calcResult(tx.profit) }))
